### ISSUE TITLE
ImapNotes V1.4-00 no longer usable on Pixel 8 with current GrapheneOS

### ISSUE THREAD

**Issue by SpameaterAtAnbraDotDe** [niendo1/ImapNotes3#100]
Texts and controls are located at the top of the screen behind the status bar and are therefore no longer usable.
Complete reinstallation does not help. Only the downgrade to the previous version helps.

**Comment by niendo1** [comment]
I will test it on the latest android version. Maybe I can find a grapheneOS image...But it will take some time...

**Comment by user00000000000000000001** [comment]
Confirming for Pixel 8 & Graphene (android version 15, kernel 5.15.170-android14-11-gf0d7580141e5 if that matters).

Not only was the account controls bar (with account name) at the very top and seemingly un-tap-able, but the "ImapNotes3" toolbar was "floating" overtop of most of it, at the top or slightly below iirc. And the list of files was apparently behind everything too, visible when scrolling/dragging it a little bit up and down, but clicking on the top notes was also impossible.

**Comment by niendo1** [comment]
It happens on VanillaIceCream API 35 as well. Even in the emulator. So its not a Graphene issue

**Comment by e2jk** [comment]
Great to see this has been fixed in the development version. 
Hopefully you can release a new version soon, as it is currently unusable (for example, you can't select the top 2 notes - which are the most recent in the default filter)

(As hopefully a way to give some value back, and give you an incentive to release a new version, I've just translated the program into French #103 . Thanks for your very useful program)
