### ISSUE TITLE
Source files lack license headers

### ISSUE THREAD

**Issue by opk12** [niendo1/ImapNotes3#15]
The FSF GPL usage [instructions say](https://www.gnu.org/licenses/gpl-howto.html) that each source file needs a proper license header.

**Comment by niendo1** [comment]
For the files I created  I will do this.
I only can assume the license of the other files..because the complete project is gpl v3.
But the FSF GPL instruction says we can not. (otherwise not every file would need a license header).

Only the creator of the files can set the license. As I'm not the creator, I can't.

I can only add a header, which says this is maybe gpl - until the creator of the files say something else...

Anybody knows what to do in this case?

**Comment by opk12** [comment]
Hi,

Thanks for answering. If the whole is GPL3, then the files are GPL3 or relicenseable as such; it's not like somewhere is mentioned an exception or another license. (where do the instructions say otherwise?) The header is a convenience for those who only see one file (also, it is not required by F-droid).

Checking the entire commit history would be time-consuming and error-prone, and the svn-to-git history conversion may have missed someone. Other projects attribute the copyright to `the project contributors` or `ImapNotes3 contributors`; or use an SPDX header ([example](https://github.com/systemd/systemd/blob/main/src/busctl/busctl-introspect.c)) which, in the case of GPL3-only, reduces to one line

    // SPDX-License-Identifier: GPL-3.0-only
