### ISSUE TITLE
E-mail format

### ISSUE THREAD

**Issue by opk12** [niendo1/ImapNotes3#19]
This app is promising. An interoperable content type would allow to
- read notes on the PC
- read notes on other phone apps (I dislike vendor lock-in)
- use the phone as input device for the pc: take info on the road or do the inventory, sync, parse on the pc in python

If I understand correctly, the app can read `text/plain`, `text/html`, `text/x-stickynote`, but it always writes `text/x-stickynote` (in [StickyNote.GetMessageFromNote()](https://github.com/niendo1/ImapNotes3/blob/master/ImapNotes3/src/main/java/de/niendo/ImapNotes3/Miscs/StickyNote.java#L143)).

This format
- apparently is non-standard / not found on the Internet
- cannot work in other apps: claws-mail shows the HTML source, k-9 shows empty body and an attachment that won't open
- requires me to reinvent the custom parser (even when only the body is of interest) and maintain it when something changes in this app

What about changing the writer to output
- a standard plain or HTML e-mail (maybe preserving the content type which was read, so messages intended to be machine-readable are not forcibly converted to html)
- a JSON attachment for metadata (common format with builtin support in the mainstream programming languages and simpler API than XML), for example with [`javax.json`](https://docs.oracle.com/javaee/7/api/javax/json/package-summary.html)

**Comment by niendo1** [comment]
https://jpmens.net/2015/09/28/experiments-using-imap-for-notes/

**Comment by opk12** [comment]
As a programmer: Maintaining a custom format is a waste of time, painful, error-prone, and teaches you almost nothing.

They are examples of compatibility with a proprietary service; only Apple users / Kolab users are interested in them.

For clarity: I do not ask to remove special info. I ask to use standard formats for special info.

**Comment by niendo1** [comment]
ImapNotes3 just saves Standard-Emails with HTML text.
For the Background-Color I used the the Background color in html style. So sometime the whole HTML-Body is saved. (inclusive <html> and <body>. I'm not sure, if this is a good idea.
Sticky-Notes will only be saved, if you check "Sticky-Notes" in the account settings. This is for a desktop notes tool.
I don't know, if somebody is using this tool..and if it is working at all. So maybe this option will be removed.

I don't know, which other standards should be supported. At least there should be some user..otherwise its useless work.
* plain text
* Mutlipart-messages
* Apple-Notes
* kolab format

If a lot of people want plain text, then it should be this way:
The message will be saved in the same format, as it was loaded.
Only new messages will be saved as html (or whatever)
Users have the possibility to change the format for each note in the editor.
--> this shouldn't be to complicated, if it is really needed.

Some Mailer (like posteo) have an own note editor, which works with a limited number of html tags..so a lot information will be lost, if I save it there. So much about the html standard.

**Comment by niendo1** [comment]
How to save meta data (for category, color and more?):
there are many ways to save meta data:
Local Database: sync with other devices is not working
Mail Header: will be removed by standard programs
one note/message which holds all the meta data as table: maybe slow
Include in HTML head (meta tag): will also be removed by some clients
include in Message directly, like <p id="category">keyword1</p>..with some special CSS
as text, just the words
Use the title for category like "keyword1 / keyword2 / title"..and use it to have folder like structure of the notes.
as email attachment as you mentioned:  makes only sense if we support attachments at all

everything in the text itself, will be supported by other standard tools. - maybe attachments too..

**Comment by niendo1** [comment]
I really would love to have a desktop version. I don't know why it is not possible to run or compile the apk to run on desktop.
I testes some android emulators..but this is to complicated for daily use.
So I stick on the HTML-Interface of the posteo notes editior.

**Comment by opk12** [comment]
Ah then I'm sorry. I did not understand the option "Sticky Notes" in the account settings and had it enabled. So I close this issue.

The Android (Dalvik) libraries do not exist on GNU/Linux (blame Google). So a cross-platform app cannot use `android.view` directly. Instead it uses a cross-platform library that chooses the backend at runtime, for example Qt ([here is an introduction](https://doc.qt.io/qt-6/android.html)).
