### ISSUE TITLE
Add encryption

### ISSUE THREAD

**Issue by woheller69** [niendo1/ImapNotes3#7]
What about adding AES encryption to the notes before uploading to the server?
-Define a key in settings
-encrypt/decrypt during sync

**Comment by niendo1** [comment]
Encryption on the server is maybe not so important, if you cant trust your email server..maybe its not good to save data there.
And some provider or other tools allow you to edit your notes via webbrowser, so you can work with your notes on your pc. this is not possible if the notes are encrypted. I use it with posteo.de. They have a very limited HTML editor for notes
But, If there is need to encrypt some notes on the server this can be added - each with a password which is not saved anywhere.

But more important, i guess, is encrypt the messages on the mobile itself. this should be done.
Here I'm not sure how to save the key phrase.
My time (and skills) is at the moment very limited. so it will take some time.

**Comment by woheller69** [comment]
you can store the key phrase in AndroidKeyStore

https://medium.com/@josiassena/using-the-android-keystore-system-to-store-sensitive-information-3a56175a454b

**Comment by opk12** [comment]
Please don't roll your own crypto (instead delegate to ready-made tools and formats) and do sign-and-encrypt (not just encrypt). See the top 2 answers [here](https://security.stackexchange.com/questions/2202).

For example, the [K-9 e-mail client](https://f-droid.org/en/packages/com.fsck.k9/) delegates encryption and key management to an OpenPGP implementation app (called [OpenKeychain](https://f-droid.org/en/packages/org.sufficientlysecure.keychain/)) which is optionally installed separately.

OpenPGP is the de-facto standard for encrypted email and is the de-facto standard in the free software world for archived [data at rest](https://en.wikipedia.org/wiki/Data_at_rest). It would make notes compatible with any current and future e-mail clients, and readable if/when this app becomes unmaintained. It also avoids security issues in K-9 due to poor secret management or poor choice of the encryption parameters, and brings for free the benefits of the envelope format which you would not get with bare AES.
